language: python
python:
  - "3.6"
install:
  - pip install -e .[dev]
script:
  - nosetests --cover-package=amcat4  --with-coverage --cover-xml
  - codecov
# (following https://docs.travis-ci.com/user/database-setup/#elasticsearch)
before_install:
  - curl https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.11.1-amd64.deb -o elasticsearch.deb
  - sudo dpkg -i --force-confnew elasticsearch.deb
  - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
  - sudo service elasticsearch restart
before_script:
  - sleep 10
